from flask import session, redirect, url_for, render_template, request, send_from_directory
from . import main
from .forms import LoginForm
import random


@main.route('/', methods=['GET', 'POST'])
def index():
    """"Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        session['password'] = form.password.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form)


@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    if 'avatar' not in session:
        session['avatar'] = get_avatar()
    data = {
        'name': session.get('name', ''),
        'avatar': session.get('avatar'),
        'room': session.get('room', ''),
        'password': session.get('password', '')
    }
    if data['name'] == '' or data['room'] == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', **data)


def get_avatar():
    imgs = [
        'Baby_48.png',
        'boy-1.png',
        'boy-2.png',
        'boy-3.png',
        'boy-4.png',
        'boy-5.png',
        'boy-6.png',
        'boy-7.png',
        'boy-8.png',
        'boy-group.png',
        'boy.png',
        'business-comunication.png',
        'businessman-1.png',
        'businessman-2.png',
        'businessman-3.png',
        'businessman-4.png',
        'businessman-and-pie-chart.png',
        'businessman.png',
        'businessman-presentation-1.png',
        'businessman-presentation.png',
        'businessmen-1.png',
        'businessmen-2.png',
        'businessmen-3.png',
        'businessmen-4.png',
        'businessmen-5.png',
        'businessmen.png',
        'businesswoman.png',
        'call-center-girl.png',
        'couple-of-girls.png',
        'EditorTeacher_48.png',
        'female-group-1.png',
        'female-group-2.png',
        'female-group-3.png',
        'female-group-4.png',
        'female-group.png',
        'female-network.png',
        'female.png',
        'female-user.png',
        'femenine-group.png',
        'girl-10.png',
        'girl-1.png',
        'girl-2.png',
        'girl-3.png',
        'girl-4.png',
        'girl-5.png',
        'girl-6.png',
        'girl-7.png',
        'girl-8.png',
        'girl-9.png',
        'girl.png',
        'girl-polaroid-pictures.png',
        'girls-group.png',
        'girl-talking-1.png',
        'girl-talking.png',
        'girl-thinking.png',
        'graphic.png',
        'group-10.png',
        'group-11.png',
        'group-12.png',
        'group-13.png',
        'group-14.png',
        'group-15.png',
        'group-16.png',
        'group-17.png',
        'group-18.png',
        'group-1.png',
        'group-2.png',
        'group-3.png',
        'group-4.png',
        'group-5.png',
        'group-6.png',
        'group-7.png',
        'group-8.png',
        'group-9.png',
        'group-of-men.png',
        'group.png',
        'hierarchy.png',
        'id-card-1.png',
        'id-card.png',
        'identification.png',
        'line-graph-and-men.png',
        'loudspeaker-and-women.png',
        'male.png',
        'male-user.png',
        'male-users-group.png',
        'male-users-scheme.png',
        'man-10.png',
        'man-11.png',
        'man-12.png',
        'man-13.png',
        'man-14.png',
        'man-15.png',
        'man-16.png',
        'man-17.png',
        'man-18.png',
        'man-19.png',
        'man-1.png',
        'man-20.png',
        'man-21.png',
        'man-22.png',
        'man-23.png',
        'man-24.png',
        'man-25.png',
        'man-26.png',
        'man-27.png',
        'man-28.png',
        'man-29.png',
        'man-2.png',
        'man-30.png',
        'man-31.png',
        'man-32.png',
        'man-33.png',
        'man-3.png',
        'man-4.png',
        'man-5.png',
        'man-6.png',
        'man-7.png',
        'man-8.png',
        'man-9.png',
        'man.png',
        'man-polaroid-pictures-1.png',
        'man-polaroid-pictures.png',
        'man-talking.png',
        'man-thinking.png',
        'men-1.png',
        'men-2.png',
        'men-3.png',
        'men.png',
        'Merchant_48.png',
        'networking-1.png',
        'networking-2.png',
        'networking.png',
        'notebook.png',
        'Nurse_48.png',
        'placeholder-1.png',
        'placeholder.png',
        'Professor_OldMan_48.png',
        'scheme.png',
        'screen-1.png',
        'screen-2.png',
        'screen.png',
        'searching-user-1.png',
        'searching-user.png',
        'search-user.png',
        'social-connections.png',
        'social-network.png',
        'SPY_48.png',
        'tablet-1.png',
        'tablet.png',
        'tablet-with-graph.png',
        'telemarketer-1.png',
        'telemarketer.png',
        'television-1.png',
        'television.png',
        'Thief_48.png',
        'user-1.png',
        'user-2.png',
        'user-3.png',
        'user-4.png',
        'user-placeholder.png',
        'user.png',
        'users-graphic.png',
        'users.png',
        'user-woman-polaroid-pictures.png',
        'woman-10.png',
        'woman-11.png',
        'woman-12.png',
        'woman-13.png',
        'woman-14.png',
        'woman-15.png',
        'woman-16.png',
        'woman-17.png',
        'woman-18.png',
        'woman-19.png',
        'woman-1.png',
        'woman-20.png',
        'woman-21.png',
        'woman-22.png',
        'woman-23.png',
        'woman-24.png',
        'woman-25.png',
        'woman-26.png',
        'woman-27.png',
        'woman-28.png',
        'woman-29.png',
        'woman-2.png',
        'woman-30.png',
        'woman-3.png',
        'woman-4.png',
        'woman-5.png',
        'woman-6.png',
        'woman-7.png',
        'woman-8.png',
        'woman-9.png',
        'woman-and-man.png',
        'woman-close-up.png',
        'woman.png',
        'woman-with-graphic.png',
        'woman-with-minus.png',
        'womem-talking.png',
        'women-1.png',
        'women-2.png',
        'women-3.png',
        'women-connections.png',
        'women.png',
        'work-hierarchy.png',
        'young-businessman.png'
    ]
    return imgs[random.randrange(0, len(imgs) - 1)]

# End File: app/main/routes.py
